name: Fix Sub Ouput
    
on:
    push:
        branches:
          - master

    workflow_dispatch:
    schedule:
        - cron: '0 */3 * * *'
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch content from URL and update file
        run: |
          # Fetch content from URL
          curl -L "${{ secrets.INPUT_URL }}" | base64 --decode > ./sub

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8

      - name: Run script
        run: |
            python python/replace.py
        
      - name: Commit UTF-8 and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update file from URL"
          git push

      - name: Run Supported SpeedTest
        run: |
            python python/pretest.py

      - name: Commit Pretest
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Pretest acquired"
          git push 
            
      - name: Convert to Base64
        run: |
          base64 sub > sub64
          content=$(cat python/pretest | base64 | tr -d '\n')
            echo "$content" > python/pretest64

      - name: Commit and push in case of changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add -A
          git diff --quiet && get diff -staged --quiet || git commit -m "Convert to Base64"
          git push
 
