name: Update File from URL
    
on:
    push:
        branches:
          - main

    workflow_dispatch:
    schedule:
        - cron: '0 * * * *'
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch content from URL and update file
        run: |
          # Fetch content from URL
          curl -L "${{ secrets.INPUT_URL }}" | base64 --decode | sed 's#none://#vmess://#g' | sed 's#auto://#vmess://#g' > ./sub

      - name: Commit UTF-8 and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update file from URL"
          git push

      - name: Convert to Base64
        run: |
          base64 sub > sub64

      - name: Commit and push in case of changes
        run: |
          git config --local user.email "action@github.com
          git config --local user.name "Github Action"
          git add -A
          git diff --quiet && get diff -staged --quiet || git commit -m "Convert to Base64"
          git push
 
